const achievementsDB = [
    // --- 🟢 EASY (1-50) ---
    { id: "e_01", category: "easy", type: "count", target: 1, xp: 10, icon: "fas fa-egg", name: {ru: "Начало начал", en: "The Beginning", it: "L'Inizio"}, desc: {ru: "Добавить первый продукт в инвентарь.", en: "Add your first item.", it: "Aggiungi il primo oggetto."} },
    { id: "e_02", category: "easy", type: "any_cook", target: 1, xp: 15, icon: "fas fa-utensil-spoon", name: {ru: "Я у мамы повар", en: "Mom's Chef", it: "Cuoco"}, desc: {ru: "Приготовить первое блюдо в приложении.", en: "Cook your first dish.", it: "Cucina il primo piatto."} },
    { id: "e_03", category: "easy", type: "count_vegetables", target: 3, xp: 15, icon: "fas fa-carrot", name: {ru: "Витаминка", en: "Vitamin"}, desc: {ru: "Купить 3 разных овоща.", en: "Buy 3 veggies."} },
    { id: "e_04", category: "easy", type: "count_fruits", target: 3, xp: 15, icon: "fas fa-apple-alt", name: {ru: "Ньютон", en: "Newton"}, desc: {ru: "3 фрукта в запасе.", en: "3 fruits in stock."} },
    { id: "e_05", category: "easy", type: "count_dairy", target: 2, xp: 15, icon: "fas fa-glass-whiskey", name: {ru: "Усатый нянь", en: "Milk Moustache"}, desc: {ru: "2 молочных продукта.", en: "2 dairy items."} },
    { id: "e_06", category: "easy", type: "breakfast_cook", target: 1, xp: 20, icon: "fas fa-sun", name: {ru: "Доброе утро", en: "Good Morning"}, desc: {ru: "Приготовить завтрак.", en: "Cook breakfast."} },
    { id: "e_07", category: "easy", type: "count", target: 5, xp: 10, icon: "fas fa-hand-paper", name: {ru: "Дай пять", en: "High Five"}, desc: {ru: "5 продуктов в холодильнике.", en: "5 items in fridge."} },
    { id: "e_08", category: "easy", type: "count_meat", target: 2, xp: 20, icon: "fas fa-drumstick-bite", name: {ru: "Хищник Jr.", en: "Predator Jr."}, desc: {ru: "2 мясных продукта.", en: "2 meat items."} },
    { id: "e_09", category: "easy", type: "pasta_cook", target: 1, xp: 20, icon: "fas fa-bacon", name: {ru: "Аль Денте", en: "Al Dente"}, desc: {ru: "Сварить макароны.", en: "Cook pasta."} },
    { id: "e_10", category: "easy", type: "soup_cook", target: 1, xp: 20, icon: "fas fa-mug-hot", name: {ru: "Жиденькое", en: "Soup Time"}, desc: {ru: "Приготовить суп.", en: "Cook a soup."} },
    { id: "e_11", category: "easy", type: "count", target: 10, xp: 25, icon: "fas fa-shopping-basket", name: {ru: "Маленькая закупка", en: "Small Haul"}, desc: {ru: "10 продуктов в инвентаре.", en: "10 items collected."} },
    { id: "e_12", category: "easy", type: "dessert_cook", target: 1, xp: 20, icon: "fas fa-cookie", name: {ru: "Сладкий зуб", en: "Sweet Tooth"}, desc: {ru: "Приготовить десерт.", en: "Cook a dessert."} },
    { id: "e_13", category: "easy", type: "salad_cook", target: 1, xp: 20, icon: "fas fa-leaf", name: {ru: "Кролик", en: "Rabbit"}, desc: {ru: "Сделать салат.", en: "Make a salad."} },
    { id: "e_14", category: "easy", type: "drinks_cook", target: 1, xp: 15, icon: "fas fa-cocktail", name: {ru: "Бармен", en: "Bartender"}, desc: {ru: "Смешать напиток.", en: "Mix a drink."} },
    { id: "e_15", category: "easy", type: "snacks_cook", target: 1, xp: 15, icon: "fas fa-hamburger", name: {ru: "Перекус", en: "Snack Time"}, desc: {ru: "Сделать закуску.", en: "Make a snack."} },
    { id: "e_16", category: "easy", type: "count_bakery", target: 3, xp: 20, icon: "fas fa-bread-slice", name: {ru: "Хлебушек", en: "Bread Lover"}, desc: {ru: "3 выпечки в запасе.", en: "3 bakery items."} },
    { id: "e_17", category: "easy", type: "count_seafood", target: 1, xp: 20, icon: "fas fa-fish", name: {ru: "Рыбка", en: "Fishy"}, desc: {ru: "1 морепродукт.", en: "1 seafood item."} },
    { id: "e_18", category: "easy", type: "count_condiments", target: 2, xp: 15, icon: "fas fa-pepper-hot", name: {ru: "Остринка", en: "Spicy"}, desc: {ru: "2 специи.", en: "2 condiments."} },
    { id: "e_19", category: "easy", type: "count_cereals", target: 2, xp: 15, icon: "fas fa-seedling", name: {ru: "Каша — сила", en: "Porridge Power"}, desc: {ru: "2 крупы.", en: "2 cereals."} },
    { id: "e_20", category: "easy", type: "any_cook", target: 5, xp: 30, icon: "fas fa-star", name: {ru: "Стажер", en: "Intern"}, desc: {ru: "5 блюд готово.", en: "5 dishes cooked."} },
    { id: "e_21", category: "easy", type: "count", target: 12, xp: 20, icon: "fas fa-box-open", name: {ru: "Дюжина", en: "Dozen"}, desc: {ru: "12 продуктов.", en: "12 items."} },
    { id: "e_22", category: "easy", type: "meat_cook", target: 2, xp: 25, icon: "fas fa-bone", name: {ru: "Двойной удар", en: "Double Strike"}, desc: {ru: "2 мясных блюда.", en: "2 meat dishes."} },
    { id: "e_23", category: "easy", type: "vegetable_cook", target: 5, xp: 25, icon: "fas fa-tractor", name: {ru: "Огород", en: "Garden"}, desc: {ru: "5 овощных блюд.", en: "5 vegetable dishes."} },
    { id: "e_24", category: "easy", type: "baking_cook", target: 1, xp: 20, icon: "fas fa-birthday-cake", name: {ru: "Пирогов", en: "Pirogov"}, desc: {ru: "Испечь что-то.", en: "Bake something."} },
    { id: "e_25", category: "easy", type: "main_cook", target: 3, xp: 25, icon: "fas fa-drumstick-bite", name: {ru: "Сытый папа", en: "Full Dad"}, desc: {ru: "3 основных блюда.", en: "3 main courses."} },
    { id: "e_26", category: "easy", type: "count_fruits", target: 5, xp: 20, icon: "fas fa-lemon", name: {ru: "Лимонад", en: "Lemonade"}, desc: {ru: "5 фруктов.", en: "5 fruits."} },
    { id: "e_27", category: "easy", type: "count_dairy", target: 5, xp: 20, icon: "fas fa-cheese", name: {ru: "Мышь", en: "Mouse"}, desc: {ru: "5 молочных.", en: "5 dairy."} },
    { id: "e_28", category: "easy", type: "breakfast_cook", target: 3, xp: 25, icon: "fas fa-coffee", name: {ru: "Кофеман", en: "Coffee Addict"}, desc: {ru: "3 завтрака.", en: "3 breakfasts."} },
    { id: "e_29", category: "easy", type: "soup_cook", target: 3, xp: 25, icon: "fas fa-spoon", name: {ru: "Половник", en: "Ladle"}, desc: {ru: "3 супа.", en: "3 soups."} },
    { id: "e_30", category: "easy", type: "count", target: 15, xp: 30, icon: "fas fa-shopping-bag", name: {ru: "Пакет с пакетами", en: "Bag of Bags"}, desc: {ru: "15 продуктов.", en: "15 items."} },
    { id: "e_31", category: "easy", type: "count_meat", target: 5, xp: 30, icon: "fas fa-piggy-bank", name: {ru: "Шашлычник", en: "BBQ Man"}, desc: {ru: "5 мясных продуктов.", en: "5 meat items."} },
    { id: "e_32", category: "easy", type: "count_vegetables", target: 8, xp: 30, icon: "fas fa-holly-berry", name: {ru: "Грядка", en: "Patch"}, desc: {ru: "8 овощей.", en: "8 vegetables."} },
    { id: "e_33", category: "easy", type: "pasta_cook", target: 3, xp: 25, icon: "fas fa-pizza-slice", name: {ru: "Марио", en: "Mario"}, desc: {ru: "3 пасты.", en: "3 pastas."} },
    { id: "e_34", category: "easy", type: "salad_cook", target: 3, xp: 25, icon: "fas fa-seedling", name: {ru: "ЗОЖ", en: "Healthy"}, desc: {ru: "3 салата.", en: "3 salads."} },
    { id: "e_35", category: "easy", type: "dessert_cook", target: 3, xp: 25, icon: "fas fa-candy-cane", name: {ru: "Сахарок", en: "Sugar"}, desc: {ru: "3 десерта.", en: "3 desserts."} },
    { id: "e_36", category: "easy", type: "count_cereals", target: 5, xp: 25, icon: "fas fa-wheat", name: {ru: "Мельник", en: "Miller"}, desc: {ru: "5 круп.", en: "5 cereals."} },
    { id: "e_37", category: "easy", type: "count_seafood", target: 3, xp: 30, icon: "fas fa-water", name: {ru: "Рыбак", en: "Fisherman"}, desc: {ru: "3 морепродукта.", en: "3 seafood."} },
    { id: "e_38", category: "easy", type: "count_condiments", target: 5, xp: 25, icon: "fas fa-bottle-droplet", name: {ru: "Соус-шеф", en: "Sauce Chef"}, desc: {ru: "5 соусов.", en: "5 sauces."} },
    { id: "e_39", category: "easy", type: "count_bakery", target: 5, xp: 25, icon: "fas fa-store", name: {ru: "Булочная", en: "Bakery"}, desc: {ru: "5 выпечек.", en: "5 bakery items."} },
    { id: "e_40", category: "easy", type: "any_cook", target: 10, xp: 40, icon: "fas fa-book-open", name: {ru: "Кулинар", en: "Culinarian"}, desc: {ru: "10 блюд.", en: "10 dishes."} },
    { id: "e_41", category: "easy", type: "count_dairy", target: 8, xp: 30, icon: "fas fa-ice-cream", name: {ru: "Пломбир", en: "Ice Cream"}, desc: {ru: "8 молочных.", en: "8 dairy."} },
    { id: "e_42", category: "easy", type: "count_fruits", target: 8, xp: 30, icon: "fas fa-carrot", name: {ru: "Смузи", en: "Smoothie"}, desc: {ru: "8 фруктов.", en: "8 fruits."} },
    { id: "e_43", category: "easy", type: "drinks_cook", target: 3, xp: 20, icon: "fas fa-wine-glass", name: {ru: "Сомелье", en: "Sommelier"}, desc: {ru: "3 напитка.", en: "3 drinks."} },
    { id: "e_44", category: "easy", type: "snacks_cook", target: 3, xp: 20, icon: "fas fa-cookie-bite", name: {ru: "Жор", en: "Munchies"}, desc: {ru: "3 закуски.", en: "3 snacks."} },
    { id: "e_45", category: "easy", type: "baking_cook", target: 3, xp: 25, icon: "fas fa-mitten", name: {ru: "Румяный бок", en: "Rosy Side"}, desc: {ru: "3 выпечки.", en: "3 bakings."} },
    { id: "e_46", category: "easy", type: "count", target: 20, xp: 35, icon: "fas fa-dolly", name: {ru: "Тележка", en: "Trolley"}, desc: {ru: "20 продуктов.", en: "20 items."} },
    { id: "e_47", category: "easy", type: "meat_cook", target: 5, xp: 30, icon: "fas fa-bacon", name: {ru: "Бекон", en: "Bacon"}, desc: {ru: "5 мясных блюд.", en: "5 meat dishes."} },
    { id: "e_48", category: "easy", type: "vegetable_cook", target: 8, xp: 30, icon: "fas fa-tree", name: {ru: "Веган-стайл", en: "Vegan Style"}, desc: {ru: "8 овощных блюд.", en: "8 veggie dishes."} },
    { id: "e_49", category: "easy", type: "main_cook", target: 8, xp: 30, icon: "fas fa-utensils", name: {ru: "Обед готов", en: "Lunch Ready"}, desc: {ru: "8 основных блюд.", en: "8 main courses."} },
    { id: "e_50", category: "easy", type: "any_cook", target: 15, xp: 50, icon: "fas fa-medal", name: {ru: "Почти повар", en: "Almost Chef"}, desc: {ru: "15 блюд.", en: "15 dishes."} },

    // --- 🟠 MEDIUM (51-100) ---
    { id: "m_01", category: "medium", type: "count", target: 25, xp: 50, icon: "fas fa-shopping-cart", name: {ru: "Полный холодильник", en: "Full Fridge"}, desc: {ru: "Накопить 25 продуктов.", en: "25 items in stock."} },
    { id: "m_02", category: "medium", type: "any_cook", target: 25, xp: 60, icon: "fas fa-fire", name: {ru: "На опыте", en: "Experienced"}, desc: {ru: "Приготовить 25 блюд.", en: "25 dishes cooked."} },
    { id: "m_03", category: "medium", type: "count_meat", target: 10, xp: 50, icon: "fas fa-steak", name: {ru: "Мясная лавка", en: "Butcher Shop"}, desc: {ru: "10 мясных продуктов.", en: "10 meat items."} },
    { id: "m_04", category: "medium", type: "count_vegetables", target: 15, xp: 50, icon: "fas fa-salad", name: {ru: "Садовод", en: "Gardener"}, desc: {ru: "15 овощей.", en: "15 vegetables."} },
    { id: "m_05", category: "medium", type: "soup_cook", target: 10, xp: 55, icon: "fas fa-cloud-meatball", name: {ru: "Суп Харчо", en: "Soup Master"}, desc: {ru: "10 супов.", en: "10 soups."} },
    { id: "m_06", category: "medium", type: "dessert_cook", target: 10, xp: 55, icon: "fas fa-birthday-cake", name: {ru: "Кондитер", en: "Pastry Chef"}, desc: {ru: "10 десертов.", en: "10 desserts."} },
    { id: "m_07", category: "medium", type: "pasta_cook", target: 10, xp: 55, icon: "fas fa-cheese", name: {ru: "Итальянец", en: "Italian"}, desc: {ru: "10 паст.", en: "10 pastas."} },
    { id: "m_08", category: "medium", type: "breakfast_cook", target: 10, xp: 55, icon: "fas fa-toast", name: {ru: "Жаворонок", en: "Early Bird"}, desc: {ru: "10 завтраков.", en: "10 breakfasts."} },
    { id: "m_09", category: "medium", type: "count_dairy", target: 15, xp: 50, icon: "fas fa-cow", name: {ru: "Ферма", en: "Dairy Farm"}, desc: {ru: "15 молочных продуктов.", en: "15 dairy items."} },
    { id: "m_10", category: "medium", type: "count_fruits", target: 15, xp: 50, icon: "fas fa-lemon", name: {ru: "Фруктовый сад", en: "Orchard"}, desc: {ru: "15 фруктов.", en: "15 fruits."} },
    { id: "m_11", category: "medium", type: "count", target: 35, xp: 60, icon: "fas fa-warehouse", name: {ru: "Кладовка", en: "Pantry"}, desc: {ru: "35 продуктов.", en: "35 items."} },
    { id: "m_12", category: "medium", type: "any_cook", target: 40, xp: 70, icon: "fas fa-hat-chef", name: {ru: "Су-шеф", en: "Sous Chef"}, desc: {ru: "40 блюд.", en: "40 dishes."} },
    { id: "m_13", category: "medium", type: "meat_cook", target: 15, xp: 60, icon: "fas fa-drumstick-bite", name: {ru: "Гриль-мастер", en: "Grill Master"}, desc: {ru: "15 мясных блюд.", en: "15 meat dishes."} },
    { id: "m_14", category: "medium", type: "vegetable_cook", target: 20, xp: 60, icon: "fas fa-leaf", name: {ru: "Сила земли", en: "Earth Power"}, desc: {ru: "20 овощных блюд.", en: "20 veggie dishes."} },
    { id: "m_15", category: "medium", type: "salad_cook", target: 15, xp: 60, icon: "fas fa-carrot", name: {ru: "Фитнес", en: "Fitness"}, desc: {ru: "15 салатов.", en: "15 salads."} },
    { id: "m_16", category: "medium", type: "main_cook", target: 20, xp: 60, icon: "fas fa-utensil-spoon", name: {ru: "Кормилец", en: "Provider"}, desc: {ru: "20 основных блюд.", en: "20 main courses."} },
    { id: "m_17", category: "medium", type: "count_seafood", target: 10, xp: 65, icon: "fas fa-anchor", name: {ru: "Моряк", en: "Sailor"}, desc: {ru: "10 морепродуктов.", en: "10 seafood."} },
    { id: "m_18", category: "medium", type: "count_bakery", target: 15, xp: 55, icon: "fas fa-bread-slice", name: {ru: "Пекарня", en: "Bakery"}, desc: {ru: "15 выпечки.", en: "15 bakery items."} },
    { id: "m_19", category: "medium", type: "count_condiments", target: 10, xp: 50, icon: "fas fa-wine-bottle", name: {ru: "Алхимик", en: "Alchemist"}, desc: {ru: "10 специй.", en: "10 condiments."} },
    { id: "m_20", category: "medium", type: "count_cereals", target: 10, xp: 50, icon: "fas fa-seedling", name: {ru: "Запас на зиму", en: "Winter Stock"}, desc: {ru: "10 круп.", en: "10 cereals."} },
    { id: "m_21", category: "medium", type: "baking_cook", target: 10, xp: 60, icon: "fas fa-mitten", name: {ru: "Бабушкин пирог", en: "Grandma's Pie"}, desc: {ru: "10 выпечек.", en: "10 bakings."} },
    { id: "m_22", category: "medium", type: "snacks_cook", target: 10, xp: 50, icon: "fas fa-cookie-bite", name: {ru: "Киновечер", en: "Movie Night"}, desc: {ru: "10 закусок.", en: "10 snacks."} },
    { id: "m_23", category: "medium", type: "drinks_cook", target: 10, xp: 50, icon: "fas fa-glass-cheers", name: {ru: "Вечеринка", en: "Party Time"}, desc: {ru: "10 напитков.", en: "10 drinks."} },
    { id: "m_24", category: "medium", type: "count", target: 45, xp: 75, icon: "fas fa-cubes", name: {ru: "Склад", en: "Depot"}, desc: {ru: "45 продуктов.", en: "45 items."} },
    { id: "m_25", category: "medium", type: "count_meat", target: 20, xp: 70, icon: "fas fa-dragon", name: {ru: "Ти-Рекс", en: "T-Rex"}, desc: {ru: "20 мясных продуктов.", en: "20 meat items."} },
    { id: "m_26", category: "medium", type: "count_vegetables", target: 25, xp: 70, icon: "fas fa-tree", name: {ru: "Джунгли", en: "Jungle"}, desc: {ru: "25 овощей.", en: "25 veggies."} },
    { id: "m_27", category: "medium", type: "count_dairy", target: 20, xp: 70, icon: "fas fa-blender", name: {ru: "Милкшейк", en: "Milkshake"}, desc: {ru: "20 молочных.", en: "20 dairy."} },
    { id: "m_28", category: "medium", type: "count_fruits", target: 20, xp: 70, icon: "fas fa-apple-alt", name: {ru: "Эдем", en: "Eden"}, desc: {ru: "20 фруктов.", en: "20 fruits."} },
    { id: "m_29", category: "medium", type: "any_cook", target: 50, xp: 100, icon: "fas fa-award", name: {ru: "Золотые руки", en: "Golden Hands"}, desc: {ru: "50 блюд.", en: "50 dishes."} },
    { id: "m_30", category: "medium", type: "soup_cook", target: 20, xp: 75, icon: "fas fa-burn", name: {ru: "Зельеварение", en: "Potions"}, desc: {ru: "20 супов.", en: "20 soups."} },
    { id: "m_31", category: "medium", type: "pasta_cook", target: 20, xp: 75, icon: "fas fa-pizza-slice", name: {ru: "Крестный отец", en: "Godfather"}, desc: {ru: "20 паст.", en: "20 pastas."} },
    { id: "m_32", category: "medium", type: "breakfast_cook", target: 20, xp: 75, icon: "fas fa-sun", name: {ru: "Будильник", en: "Alarm Clock"}, desc: {ru: "20 завтраков.", en: "20 breakfasts."} },
    { id: "m_33", category: "medium", type: "dessert_cook", target: 20, xp: 75, icon: "fas fa-candy-cane", name: {ru: "Вилли Вонка", en: "Willy Wonka"}, desc: {ru: "20 десертов.", en: "20 desserts."} },
    { id: "m_34", category: "medium", type: "count_seafood", target: 15, xp: 80, icon: "fas fa-ship", name: {ru: "Капитан", en: "Captain"}, desc: {ru: "15 морепродуктов.", en: "15 seafood."} },
    { id: "m_35", category: "medium", type: "meat_cook", target: 25, xp: 80, icon: "fas fa-hamburger", name: {ru: "Бургер Кинг", en: "Burger King"}, desc: {ru: "25 мясных блюд.", en: "25 meat dishes."} },
    { id: "m_36", category: "medium", type: "vegetable_cook", target: 30, xp: 80, icon: "fas fa-seedling", name: {ru: "Гринпис", en: "Greenpeace"}, desc: {ru: "30 овощных блюд.", en: "30 veggie dishes."} },
    { id: "m_37", category: "medium", type: "main_cook", target: 30, xp: 80, icon: "fas fa-concierge-bell", name: {ru: "Банкет", en: "Banquet"}, desc: {ru: "30 основных блюд.", en: "30 main courses."} },
    { id: "m_38", category: "medium", type: "count_bakery", target: 25, xp: 75, icon: "fas fa-birthday-cake", name: {ru: "Торт", en: "Cake Boss"}, desc: {ru: "25 выпечки.", en: "25 bakery."} },
    { id: "m_39", category: "medium", type: "count_cereals", target: 20, xp: 70, icon: "fas fa-wheat", name: {ru: "Поле чудес", en: "Field of Dreams"}, desc: {ru: "20 круп.", en: "20 cereals."} },
    { id: "m_40", category: "medium", type: "count", target: 50, xp: 100, icon: "fas fa-box", name: {ru: "Юбилей запасов", en: "Inventory Jubilee"}, desc: {ru: "50 продуктов.", en: "50 items."} },
    { id: "m_41", category: "medium", type: "salad_cook", target: 25, xp: 80, icon: "fas fa-carrot", name: {ru: "Веган", en: "Vegan"}, desc: {ru: "25 салатов.", en: "25 salads."} },
    { id: "m_42", category: "medium", type: "drinks_cook", target: 20, xp: 70, icon: "fas fa-cocktail", name: {ru: "Коктейль", en: "Cocktail"}, desc: {ru: "20 напитков.", en: "20 drinks."} },
    { id: "m_43", category: "medium", type: "snacks_cook", target: 20, xp: 70, icon: "fas fa-cookie", name: {ru: "Чипсы", en: "Chips"}, desc: {ru: "20 закусок.", en: "20 snacks."} },
    { id: "m_44", category: "medium", type: "baking_cook", target: 20, xp: 80, icon: "fas fa-bread-slice", name: {ru: "Багет", en: "Baguette"}, desc: {ru: "20 выпечек.", en: "20 bakings."} },
    { id: "m_45", category: "medium", type: "count_condiments", target: 15, xp: 60, icon: "fas fa-pepper-hot", name: {ru: "Чили", en: "Chili"}, desc: {ru: "15 специй.", en: "15 condiments."} },
    { id: "m_46", category: "medium", type: "count_dairy", target: 25, xp: 80, icon: "fas fa-glass-whiskey", name: {ru: "Сливки", en: "Cream"}, desc: {ru: "25 молочных.", en: "25 dairy."} },
    { id: "m_47", category: "medium", type: "count_fruits", target: 25, xp: 80, icon: "fas fa-apple-alt", name: {ru: "Витамин С", en: "Vitamin C"}, desc: {ru: "25 фруктов.", en: "25 fruits."} },
    { id: "m_48", category: "medium", type: "any_cook", target: 60, xp: 120, icon: "fas fa-fire-alt", name: {ru: "Горячая кухня", en: "Hell's Kitchen"}, desc: {ru: "60 блюд.", en: "60 dishes."} },
    { id: "m_49", category: "medium", type: "count_meat", target: 30, xp: 90, icon: "fas fa-bone", name: {ru: "Стейк Хаус", en: "Steak House"}, desc: {ru: "30 мяса.", en: "30 meat."} },
    { id: "m_50", category: "medium", type: "count_vegetables", target: 35, xp: 90, icon: "fas fa-leaf", name: {ru: "Брокколи", en: "Broccoli"}, desc: {ru: "35 овощей.", en: "35 vegetables."} },

    // --- 🔴 HARD (101-150) ---
    { id: "h_01", category: "hard", type: "count", target: 75, xp: 150, icon: "fas fa-truck-loading", name: {ru: "Завхоз", en: "Supply Manager"}, desc: {ru: "75 продуктов.", en: "75 items."} },
    { id: "h_02", category: "hard", type: "any_cook", target: 100, xp: 200, icon: "fas fa-star", name: {ru: "Шеф-повар", en: "Head Chef"}, desc: {ru: "100 блюд.", en: "100 dishes."} },
    { id: "h_03", category: "hard", type: "count_meat", target: 40, xp: 150, icon: "fas fa-drumstick-bite", name: {ru: "Мясной король", en: "Meat King"}, desc: {ru: "40 мясных продуктов.", en: "40 meat items."} },
    { id: "h_04", category: "hard", type: "count_vegetables", target: 50, xp: 150, icon: "fas fa-tractor", name: {ru: "Агроном", en: "Agronomist"}, desc: {ru: "50 овощей.", en: "50 vegetables."} },
    { id: "h_05", category: "hard", type: "soup_cook", target: 50, xp: 180, icon: "fas fa-cauldron", name: {ru: "Ведьмак", en: "The Witcher"}, desc: {ru: "50 супов.", en: "50 soups."} },
    { id: "h_06", category: "hard", type: "pasta_cook", target: 50, xp: 180, icon: "fas fa-city", name: {ru: "Император Рима", en: "Emperor of Rome"}, desc: {ru: "50 паст.", en: "50 pastas."} },
    { id: "h_07", category: "hard", type: "dessert_cook", target: 50, xp: 180, icon: "fas fa-stroopwafel", name: {ru: "Диабет", en: "Sugar Rush"}, desc: {ru: "50 десертов.", en: "50 desserts."} },
    { id: "h_08", category: "hard", type: "breakfast_cook", target: 50, xp: 180, icon: "fas fa-egg", name: {ru: "День сурка", en: "Groundhog Day"}, desc: {ru: "50 завтраков.", en: "50 breakfasts."} },
    { id: "h_09", category: "hard", type: "count_seafood", target: 30, xp: 160, icon: "fas fa-fish", name: {ru: "Посейдон", en: "Poseidon"}, desc: {ru: "30 морепродуктов.", en: "30 seafood."} },
    { id: "h_10", category: "hard", type: "count_bakery", target: 40, xp: 150, icon: "fas fa-bread-slice", name: {ru: "Хлебзавод", en: "Bread Factory"}, desc: {ru: "40 выпечки.", en: "40 bakery items."} },
    { id: "h_11", category: "hard", type: "count", target: 90, xp: 180, icon: "fas fa-dungeon", name: {ru: "Бункер", en: "Bunker"}, desc: {ru: "90 продуктов.", en: "90 items."} },
    { id: "h_12", category: "hard", type: "any_cook", target: 150, xp: 250, icon: "fas fa-medal", name: {ru: "Ветеран плиты", en: "Stove Veteran"}, desc: {ru: "150 блюд.", en: "150 dishes."} },
    { id: "h_13", category: "hard", type: "count_meat", target: 50, xp: 200, icon: "fas fa-skull-crossbones", name: {ru: "Палео-диета", en: "Paleo Diet"}, desc: {ru: "50 мяса.", en: "50 meat."} },
    { id: "h_14", category: "hard", type: "count_vegetables", target: 70, xp: 200, icon: "fab fa-pagelines", name: {ru: "Плантация", en: "Plantation"}, desc: {ru: "70 овощей.", en: "70 veggies."} },
    { id: "h_15", category: "hard", type: "count_dairy", target: 50, xp: 200, icon: "fas fa-cheese", name: {ru: "Сыроварня", en: "Cheese Factory"}, desc: {ru: "50 молочных.", en: "50 dairy."} },
    { id: "h_16", category: "hard", type: "count_fruits", target: 50, xp: 200, icon: "fas fa-lemon", name: {ru: "Тропики", en: "Tropics"}, desc: {ru: "50 фруктов.", en: "50 fruits."} },
    { id: "h_17", category: "hard", type: "meat_cook", target: 40, xp: 200, icon: "fas fa-bacon", name: {ru: "Мясоед", en: "Carnivore"}, desc: {ru: "40 мясных блюд.", en: "40 meat dishes."} },
    { id: "h_18", category: "hard", type: "vegetable_cook", target: 40, xp: 200, icon: "fas fa-leaf", name: {ru: "Травоядный", en: "Herbivore"}, desc: {ru: "40 овощных блюд.", en: "40 veggie dishes."} },
    { id: "h_19", category: "hard", type: "salad_cook", target: 40, xp: 200, icon: "fas fa-carrot", name: {ru: "Фитнес-гуру", en: "Fitness Guru"}, desc: {ru: "40 салатов.", en: "40 salads."} },
    { id: "h_20", category: "hard", type: "main_cook", target: 50, xp: 200, icon: "fas fa-concierge-bell", name: {ru: "Ресторатор", en: "Restaurateur"}, desc: {ru: "50 основных блюд.", en: "50 main courses."} },
    { id: "h_21", category: "hard", type: "baking_cook", target: 30, xp: 200, icon: "fas fa-mitten", name: {ru: "Пироговая", en: "Pie Shop"}, desc: {ru: "30 выпечек.", en: "30 bakings."} },
    { id: "h_22", category: "hard", type: "drinks_cook", target: 30, xp: 180, icon: "fas fa-glass-martini-alt", name: {ru: "Бар-менеджер", en: "Bar Manager"}, desc: {ru: "30 напитков.", en: "30 drinks."} },
    { id: "h_23", category: "hard", type: "snacks_cook", target: 30, xp: 180, icon: "fas fa-cookie", name: {ru: "Фастфуд", en: "Fast Food"}, desc: {ru: "30 закусок.", en: "30 snacks."} },
    { id: "h_24", category: "hard", type: "count_cereals", target: 30, xp: 160, icon: "fas fa-seedling", name: {ru: "Амбар", en: "Barn"}, desc: {ru: "30 круп.", en: "30 cereals."} },
    { id: "h_25", category: "hard", type: "count_condiments", target: 20, xp: 150, icon: "fas fa-pepper-hot", name: {ru: "Специи Дюны", en: "Spice of Dune"}, desc: {ru: "20 специй.", en: "20 condiments."} },
    { id: "h_26", category: "hard", type: "count", target: 100, xp: 250, icon: "fas fa-box", name: {ru: "Сотня", en: "The Hundred"}, desc: {ru: "100 продуктов.", en: "100 items."} },
    { id: "h_27", category: "hard", type: "any_cook", target: 200, xp: 350, icon: "fas fa-utensils", name: {ru: "Мастер", en: "Master"}, desc: {ru: "200 блюд.", en: "200 dishes."} },
    { id: "h_28", category: "hard", type: "soup_cook", target: 60, xp: 220, icon: "fas fa-mug-hot", name: {ru: "Горячий цех", en: "Hot Station"}, desc: {ru: "60 супов.", en: "60 soups."} },
    { id: "h_29", category: "hard", type: "pasta_cook", target: 60, xp: 220, icon: "fas fa-pizza-slice", name: {ru: "Мафиози", en: "Mafioso"}, desc: {ru: "60 паст.", en: "60 pastas."} },
    { id: "h_30", category: "hard", type: "dessert_cook", target: 60, xp: 220, icon: "fas fa-candy-cane", name: {ru: "Сладкая жизнь", en: "La Dolce Vita"}, desc: {ru: "60 десертов.", en: "60 desserts."} },
    { id: "h_31", category: "hard", type: "breakfast_cook", target: 60, xp: 220, icon: "fas fa-coffee", name: {ru: "Кофейня", en: "Coffee Shop"}, desc: {ru: "60 завтраков.", en: "60 breakfasts."} },
    { id: "h_32", category: "hard", type: "count_seafood", target: 40, xp: 200, icon: "fas fa-water", name: {ru: "Океанариум", en: "Oceanarium"}, desc: {ru: "40 морепродуктов.", en: "40 seafood."} },
    { id: "h_33", category: "hard", type: "count_bakery", target: 50, xp: 200, icon: "fas fa-birthday-cake", name: {ru: "Кондитерская", en: "Confectionery"}, desc: {ru: "50 выпечки.", en: "50 bakery."} },
    { id: "h_34", category: "hard", type: "meat_cook", target: 60, xp: 250, icon: "fas fa-drumstick-bite", name: {ru: "Мясник", en: "Butcher"}, desc: {ru: "60 мясных блюд.", en: "60 meat dishes."} },
    { id: "h_35", category: "hard", type: "vegetable_cook", target: 60, xp: 250, icon: "fas fa-tree", name: {ru: "Эльф", en: "Elf"}, desc: {ru: "60 овощных блюд.", en: "60 veggie dishes."} },
    { id: "h_36", category: "hard", type: "main_cook", target: 70, xp: 250, icon: "fas fa-concierge-bell", name: {ru: "Шведский стол", en: "Buffet"}, desc: {ru: "70 основных блюд.", en: "70 main courses."} },
    { id: "h_37", category: "hard", type: "count_dairy", target: 60, xp: 220, icon: "fas fa-blender", name: {ru: "Молочная река", en: "Milky Way"}, desc: {ru: "60 молочных.", en: "60 dairy."} },
    { id: "h_38", category: "hard", type: "count_fruits", target: 60, xp: 220, icon: "fas fa-apple-alt", name: {ru: "Райский сад", en: "Paradise Garden"}, desc: {ru: "60 фруктов.", en: "60 fruits."} },
    { id: "h_39", category: "hard", type: "count_cereals", target: 40, xp: 180, icon: "fas fa-wheat", name: {ru: "Элеватор", en: "Grain Elevator"}, desc: {ru: "40 круп.", en: "40 cereals."} },
    { id: "h_40", category: "hard", type: "count_condiments", target: 30, xp: 180, icon: "fas fa-pepper-hot", name: {ru: "Базар специй", en: "Spice Market"}, desc: {ru: "30 специй.", en: "30 condiments."} },
    { id: "h_41", category: "hard", type: "salad_cook", target: 50, xp: 220, icon: "fas fa-carrot", name: {ru: "Цезарь", en: "Caesar"}, desc: {ru: "50 салатов.", en: "50 salads."} },
    { id: "h_42", category: "hard", type: "drinks_cook", target: 40, xp: 200, icon: "fas fa-cocktail", name: {ru: "Миксолог", en: "Mixologist"}, desc: {ru: "40 напитков.", en: "40 drinks."} },
    { id: "h_43", category: "hard", type: "snacks_cook", target: 40, xp: 200, icon: "fas fa-cookie", name: {ru: "Тапас", en: "Tapas"}, desc: {ru: "40 закусок.", en: "40 snacks."} },
    { id: "h_44", category: "hard", type: "baking_cook", target: 40, xp: 220, icon: "fas fa-bread-slice", name: {ru: "Круассан", en: "Croissant"}, desc: {ru: "40 выпечек.", en: "40 bakings."} },
    { id: "h_45", category: "hard", type: "count", target: 110, xp: 280, icon: "fas fa-box-open", name: {ru: "Логист", en: "Logistician"}, desc: {ru: "110 продуктов.", en: "110 items."} },
    { id: "h_46", category: "hard", type: "any_cook", target: 250, xp: 400, icon: "fas fa-crown", name: {ru: "Гуру", en: "Guru"}, desc: {ru: "250 блюд.", en: "250 dishes."} },
    { id: "h_47", category: "hard", type: "count_meat", target: 60, xp: 220, icon: "fas fa-drumstick-bite", name: {ru: "Мясная империя", en: "Meat Empire"}, desc: {ru: "60 мяса.", en: "60 meat."} },
    { id: "h_48", category: "hard", type: "count_vegetables", target: 80, xp: 220, icon: "fas fa-leaf", name: {ru: "Эко-ферма", en: "Eco Farm"}, desc: {ru: "80 овощей.", en: "80 veggies."} },
    { id: "h_49", category: "hard", type: "count_seafood", target: 50, xp: 220, icon: "fas fa-anchor", name: {ru: "Рыбный порт", en: "Fish Port"}, desc: {ru: "50 морепродуктов.", en: "50 seafood."} },
    { id: "h_50", category: "hard", type: "count_bakery", target: 60, xp: 220, icon: "fas fa-store", name: {ru: "Хлебный магнат", en: "Bread Tycoon"}, desc: {ru: "60 выпечки.", en: "60 bakery."} },

    // --- 🟣 VERY HARD (151-200) ---
    { id: "vh_01", category: "very_hard", type: "count", target: 200, xp: 500, icon: "fas fa-warehouse", name: {ru: "Владелец склада", en: "Warehouse Owner"}, desc: {ru: "200 продуктов.", en: "200 items."} },
    { id: "vh_02", category: "very_hard", type: "any_cook", target: 500, xp: 1000, icon: "fas fa-utensils", name: {ru: "Звезда Мишлен", en: "Michelin Star"}, desc: {ru: "500 блюд.", en: "500 dishes."} },
    { id: "vh_03", category: "very_hard", type: "count_meat", target: 100, xp: 600, icon: "fas fa-dragon", name: {ru: "Король Лев", en: "Lion King"}, desc: {ru: "100 мясных продуктов.", en: "100 meat items."} },
    { id: "vh_04", category: "very_hard", type: "count_vegetables", target: 150, xp: 600, icon: "fas fa-tree", name: {ru: "Дриада", en: "Dryad"}, desc: {ru: "150 овощей.", en: "150 vegetables."} },
    { id: "vh_05", category: "very_hard", type: "soup_cook", target: 150, xp: 800, icon: "fas fa-pepper-hot", name: {ru: "Дракон", en: "The Dragon"}, desc: {ru: "150 супов.", en: "150 soups."} },
    { id: "vh_06", category: "very_hard", type: "pasta_cook", target: 150, xp: 800, icon: "fas fa-wine-bottle", name: {ru: "Крестный Отец", en: "The Godfather"}, desc: {ru: "150 паст.", en: "150 pastas."} },
    { id: "vh_07", category: "very_hard", type: "dessert_cook", target: 150, xp: 800, icon: "fas fa-crown", name: {ru: "Сахарный Король", en: "Sugar King"}, desc: {ru: "150 десертов.", en: "150 desserts."} },
    { id: "vh_08", category: "very_hard", type: "breakfast_cook", target: 150, xp: 800, icon: "fas fa-cocktail", name: {ru: "Король Бранчей", en: "Brunch King"}, desc: {ru: "150 завтраков.", en: "150 breakfasts."} },
    { id: "vh_09", category: "very_hard", type: "count_seafood", target: 80, xp: 700, icon: "fas fa-ship", name: {ru: "Кракен", en: "The Kraken"}, desc: {ru: "80 морепродуктов.", en: "80 seafood."} },
    { id: "vh_10", category: "very_hard", type: "count_bakery", target: 100, xp: 700, icon: "fas fa-industry", name: {ru: "Хлебокомбинат", en: "Bread Industry"}, desc: {ru: "100 выпечки.", en: "100 bakery items."} },
    { id: "vh_11", category: "very_hard", type: "count", target: 250, xp: 600, icon: "fas fa-city", name: {ru: "Супермаркет", en: "Supermarket"}, desc: {ru: "250 продуктов.", en: "250 items."} },
    { id: "vh_12", category: "very_hard", type: "any_cook", target: 600, xp: 1200, icon: "fas fa-star-half-alt", name: {ru: "Шеф Вселенной", en: "Universal Chef"}, desc: {ru: "600 блюд.", en: "600 dishes."} },
    { id: "vh_13", category: "very_hard", type: "meat_cook", target: 100, xp: 800, icon: "fas fa-bone", name: {ru: "Мясная Фабрика", en: "Meat Factory"}, desc: {ru: "100 мясных блюд.", en: "100 meat dishes."} },
    { id: "vh_14", category: "very_hard", type: "vegetable_cook", target: 100, xp: 800, icon: "fas fa-leaf", name: {ru: "Сильвана", en: "Sylvanas"}, desc: {ru: "100 овощных блюд.", en: "100 veggie dishes."} },
    { id: "vh_15", category: "very_hard", type: "salad_cook", target: 100, xp: 800, icon: "fas fa-carrot", name: {ru: "Король Салатов", en: "Salad King"}, desc: {ru: "100 салатов.", en: "100 salads."} },
    { id: "vh_16", category: "very_hard", type: "main_cook", target: 150, xp: 850, icon: "fas fa-utensils", name: {ru: "Пир горой", en: "Grand Feast"}, desc: {ru: "150 основных блюд.", en: "150 main courses."} },
    { id: "vh_17", category: "very_hard", type: "count_dairy", target: 100, xp: 700, icon: "fas fa-cheese", name: {ru: "Молочник", en: "Milkman"}, desc: {ru: "100 молочных.", en: "100 dairy."} },
    { id: "vh_18", category: "very_hard", type: "count_fruits", target: 100, xp: 700, icon: "fas fa-lemon", name: {ru: "Тропики", en: "Tropics"}, desc: {ru: "100 фруктов.", en: "100 fruits."} },
    { id: "vh_19", category: "very_hard", type: "baking_cook", target: 80, xp: 750, icon: "fas fa-bread-slice", name: {ru: "Пекарь 80 lvl", en: "Lvl 80 Baker"}, desc: {ru: "80 выпечек.", en: "80 bakings."} },
    { id: "vh_20", category: "very_hard", type: "drinks_cook", target: 80, xp: 750, icon: "fas fa-glass-whiskey", name: {ru: "Бармен от бога", en: "Godlike Bartender"}, desc: {ru: "80 напитков.", en: "80 drinks."} },
    { id: "vh_21", category: "very_hard", type: "snacks_cook", target: 80, xp: 750, icon: "fas fa-cookie-bite", name: {ru: "Снек-Мастер", en: "Snack Master"}, desc: {ru: "80 закусок.", en: "80 snacks."} },
    { id: "vh_22", category: "very_hard", type: "count_cereals", target: 80, xp: 600, icon: "fas fa-wheat", name: {ru: "Зернохранилище", en: "Granary"}, desc: {ru: "80 круп.", en: "80 cereals."} },
    { id: "vh_23", category: "very_hard", type: "count_condiments", target: 60, xp: 600, icon: "fas fa-pepper-hot", name: {ru: "Вкус Востока", en: "Taste of East"}, desc: {ru: "60 специй.", en: "60 condiments."} },
    { id: "vh_24", category: "very_hard", type: "count", target: 300, xp: 700, icon: "fas fa-building", name: {ru: "Гипермаркет", en: "Hypermarket"}, desc: {ru: "300 продуктов.", en: "300 items."} },
    { id: "vh_25", category: "very_hard", type: "any_cook", target: 700, xp: 1400, icon: "fas fa-trophy", name: {ru: "Легенда Кухни", en: "Kitchen Legend"}, desc: {ru: "700 блюд.", en: "700 dishes."} },
    { id: "vh_26", category: "very_hard", type: "count_meat", target: 120, xp: 700, icon: "fas fa-skull", name: {ru: "Кладбище", en: "Graveyard"}, desc: {ru: "120 мяса.", en: "120 meat."} },
    { id: "vh_27", category: "very_hard", type: "count_vegetables", target: 200, xp: 700, icon: "fab fa-envira", name: {ru: "Мать Природа", en: "Mother Nature"}, desc: {ru: "200 овощей.", en: "200 vegetables."} },
    { id: "vh_28", category: "very_hard", type: "soup_cook", target: 200, xp: 900, icon: "fas fa-burn", name: {ru: "Вулкан", en: "Volcano"}, desc: {ru: "200 супов.", en: "200 soups."} },
    { id: "vh_29", category: "very_hard", type: "pasta_cook", target: 200, xp: 900, icon: "fas fa-pizza-slice", name: {ru: "Римский Папа", en: "The Pope"}, desc: {ru: "200 паст.", en: "200 pastas."} },
    { id: "vh_30", category: "very_hard", type: "dessert_cook", target: 200, xp: 900, icon: "fas fa-candy-cane", name: {ru: "Инсулин", en: "Insulin"}, desc: {ru: "200 десертов.", en: "200 desserts."} },
    { id: "vh_31", category: "very_hard", type: "breakfast_cook", target: 200, xp: 900, icon: "fas fa-sun", name: {ru: "Вечное сияние", en: "Eternal Sunshine"}, desc: {ru: "200 завтраков.", en: "200 breakfasts."} },
    { id: "vh_32", category: "very_hard", type: "count_seafood", target: 100, xp: 800, icon: "fas fa-anchor", name: {ru: "Атлантида", en: "Atlantis"}, desc: {ru: "100 морепродуктов.", en: "100 seafood."} },
    { id: "vh_33", category: "very_hard", type: "count_bakery", target: 120, xp: 800, icon: "fas fa-industry", name: {ru: "Хлеб-Завод 2.0", en: "Bakery Plant"}, desc: {ru: "120 выпечки.", en: "120 bakery."} },
    { id: "vh_34", category: "very_hard", type: "meat_cook", target: 150, xp: 900, icon: "fas fa-drumstick-bite", name: {ru: "Мясная Планета", en: "Meat Planet"}, desc: {ru: "150 мясных блюд.", en: "150 meat dishes."} },
    { id: "vh_35", category: "very_hard", type: "vegetable_cook", target: 150, xp: 900, icon: "fas fa-leaf", name: {ru: "Эдемский Сад", en: "Eden Garden"}, desc: {ru: "150 овощных блюд.", en: "150 veggie dishes."} },
    { id: "vh_36", category: "very_hard", type: "main_cook", target: 200, xp: 950, icon: "fas fa-utensils", name: {ru: "Королевский пир", en: "Royal Feast"}, desc: {ru: "200 основных блюд.", en: "200 main courses."} },
    { id: "vh_37", category: "very_hard", type: "count_dairy", target: 120, xp: 750, icon: "fas fa-blender", name: {ru: "Млечный Путь", en: "Milky Way"}, desc: {ru: "120 молочных.", en: "120 dairy."} },
    { id: "vh_38", category: "very_hard", type: "count_fruits", target: 120, xp: 750, icon: "fas fa-lemon", name: {ru: "Витаминный взрыв", en: "Vitamin Blast"}, desc: {ru: "120 фруктов.", en: "120 fruits."} },
    { id: "vh_39", category: "very_hard", type: "count_cereals", target: 100, xp: 700, icon: "fas fa-seedling", name: {ru: "Запас на век", en: "Century Stock"}, desc: {ru: "100 круп.", en: "100 cereals."} },
    { id: "vh_40", category: "very_hard", type: "count_condiments", target: 80, xp: 700, icon: "fas fa-pepper-hot", name: {ru: "Шелковый путь", en: "Silk Road"}, desc: {ru: "80 специй.", en: "80 condiments."} },
    { id: "vh_41", category: "very_hard", type: "salad_cook", target: 150, xp: 900, icon: "fas fa-carrot", name: {ru: "Салатный Король", en: "Salad Lord"}, desc: {ru: "150 салатов.", en: "150 salads."} },
    { id: "vh_42", category: "very_hard", type: "drinks_cook", target: 100, xp: 800, icon: "fas fa-glass-cheers", name: {ru: "Повелитель напитков", en: "Drink Lord"}, desc: {ru: "100 напитков.", en: "100 drinks."} },
    { id: "vh_43", category: "very_hard", type: "snacks_cook", target: 100, xp: 800, icon: "fas fa-cookie", name: {ru: "Снек-Лорд", en: "Snack Lord"}, desc: {ru: "100 закусок.", en: "100 snacks."} },
    { id: "vh_44", category: "very_hard", type: "baking_cook", target: 100, xp: 800, icon: "fas fa-bread-slice", name: {ru: "Золотой Батон", en: "Golden Loaf"}, desc: {ru: "100 выпечек.", en: "100 bakings."} },
    { id: "vh_45", category: "very_hard", type: "count", target: 350, xp: 800, icon: "fas fa-dolly-flatbed", name: {ru: "Торговый Центр", en: "Mall"}, desc: {ru: "350 продуктов.", en: "350 items."} },
    { id: "vh_46", category: "very_hard", type: "any_cook", target: 800, xp: 1600, icon: "fas fa-medal", name: {ru: "Бессмертный", en: "Immortal"}, desc: {ru: "800 блюд.", en: "800 dishes."} },
    { id: "vh_47", category: "very_hard", type: "count_meat", target: 140, xp: 750, icon: "fas fa-drumstick-bite", name: {ru: "Мясная Галактика", en: "Meat Galaxy"}, desc: {ru: "140 мяса.", en: "140 meat."} },
    { id: "vh_48", category: "very_hard", type: "count_vegetables", target: 250, xp: 750, icon: "fas fa-tree", name: {ru: "Планета Земля", en: "Planet Earth"}, desc: {ru: "250 овощей.", en: "250 veggies."} },
    { id: "vh_49", category: "very_hard", type: "count_seafood", target: 120, xp: 800, icon: "fas fa-fish", name: {ru: "Аквамен", en: "Aquaman"}, desc: {ru: "120 морепродуктов.", en: "120 seafood."} },
    { id: "vh_50", category: "very_hard", type: "count_bakery", target: 140, xp: 800, icon: "fas fa-birthday-cake", name: {ru: "Тортовая Империя", en: "Cake Empire"}, desc: {ru: "140 выпечки.", en: "140 bakery."} },

    // --- 🟣 MEGA HARD (201-250) ---
    { id: "mh_01", category: "mega_hard", type: "count", target: 500, xp: 1000, icon: "fas fa-city", name: {ru: "Магнат запасов", en: "Inventory Tycoon"}, desc: {ru: "500 продуктов.", en: "500 items."} },
    { id: "mh_02", category: "mega_hard", type: "any_cook", target: 1000, xp: 2000, icon: "fas fa-crown", name: {ru: "Бог Кухни", en: "God of Kitchen"}, desc: {ru: "1000 блюд.", en: "1000 dishes."} },
    { id: "mh_03", category: "mega_hard", type: "count_meat", target: 400, xp: 1500, icon: "fas fa-dragon", name: {ru: "Динозавр", en: "T-Rex Elder"}, desc: {ru: "400 мясных продуктов.", en: "400 meat items."} },
    { id: "mh_04", category: "mega_hard", type: "count_vegetables", target: 400, xp: 1500, icon: "fab fa-pagelines", name: {ru: "Дух Леса", en: "Forest Spirit"}, desc: {ru: "400 овощей.", en: "400 vegetables."} },
    { id: "mh_05", category: "mega_hard", type: "soup_cook", target: 400, xp: 1500, icon: "fas fa-cauldron", name: {ru: "Ведьмин Котел", en: "Witch Cauldron"}, desc: {ru: "400 супов.", en: "400 soups."} },
    { id: "mh_06", category: "mega_hard", type: "pasta_cook", target: 400, xp: 1500, icon: "fas fa-landmark", name: {ru: "Колизей", en: "Colosseum"}, desc: {ru: "400 паст.", en: "400 pastas."} },
    { id: "mh_07", category: "mega_hard", type: "dessert_cook", target: 400, xp: 1500, icon: "fas fa-stroopwafel", name: {ru: "Империя Сласти", en: "Candy Empire"}, desc: {ru: "400 десертов.", en: "400 desserts."} },
    { id: "mh_08", category: "mega_hard", type: "breakfast_cook", target: 400, xp: 1500, icon: "fas fa-cocktail", name: {ru: "Вечный Завтрак", en: "Eternal Breakfast"}, desc: {ru: "400 завтраков.", en: "400 breakfasts."} },
    { id: "mh_09", category: "mega_hard", type: "count_seafood", target: 300, xp: 1200, icon: "fas fa-water", name: {ru: "Лох-Несс", en: "Loch Ness"}, desc: {ru: "300 морепродуктов.", en: "300 seafood."} },
    { id: "mh_10", category: "mega_hard", type: "count_bakery", target: 300, xp: 1200, icon: "fas fa-globe-europe", name: {ru: "Хлеб Мира", en: "World Bread"}, desc: {ru: "300 выпечки.", en: "300 bakery items."} },
    { id: "mh_11", category: "mega_hard", type: "count", target: 600, xp: 1200, icon: "fas fa-building", name: {ru: "Мегамолл", en: "Megamall"}, desc: {ru: "600 продуктов.", en: "600 items."} },
    { id: "mh_12", category: "mega_hard", type: "any_cook", target: 1200, xp: 2500, icon: "fas fa-star", name: {ru: "Галактический Шеф", en: "Galactic Chef"}, desc: {ru: "1200 блюд.", en: "1200 dishes."} },
    { id: "mh_13", category: "mega_hard", type: "meat_cook", target: 300, xp: 1500, icon: "fas fa-drumstick-bite", name: {ru: "Мясной Бог", en: "Meat God"}, desc: {ru: "300 мясных блюд.", en: "300 meat dishes."} },
    { id: "mh_14", category: "mega_hard", type: "vegetable_cook", target: 300, xp: 1500, icon: "fas fa-leaf", name: {ru: "Гайя", en: "Gaia"}, desc: {ru: "300 овощных блюд.", en: "300 veggie dishes."} },
    { id: "mh_15", category: "mega_hard", type: "salad_cook", target: 300, xp: 1500, icon: "fas fa-carrot", name: {ru: "Повелитель Травы", en: "Herb Lord"}, desc: {ru: "300 салатов.", en: "300 salads."} },
    { id: "mh_16", category: "mega_hard", type: "main_cook", target: 400, xp: 1500, icon: "fas fa-utensils", name: {ru: "Пир Богов", en: "Gods' Feast"}, desc: {ru: "400 основных блюд.", en: "400 main courses."} },
    { id: "mh_17", category: "mega_hard", type: "count_dairy", target: 200, xp: 1000, icon: "fas fa-cheese", name: {ru: "Сырная Луна", en: "Cheese Moon"}, desc: {ru: "200 молочных.", en: "200 dairy."} },
    { id: "mh_18", category: "mega_hard", type: "count_fruits", target: 200, xp: 1000, icon: "fas fa-lemon", name: {ru: "Витаминный Бог", en: "Vitamin God"}, desc: {ru: "200 фруктов.", en: "200 fruits."} },
    { id: "mh_19", category: "mega_hard", type: "baking_cook", target: 200, xp: 1200, icon: "fas fa-birthday-cake", name: {ru: "Кондитер Вселенной", en: "Universal Baker"}, desc: {ru: "200 выпечек.", en: "200 bakings."} },
    { id: "mh_20", category: "mega_hard", type: "drinks_cook", target: 200, xp: 1200, icon: "fas fa-glass-martini", name: {ru: "Дионис", en: "Dionysus"}, desc: {ru: "200 напитков.", en: "200 drinks."} },
    { id: "mh_21", category: "mega_hard", type: "snacks_cook", target: 200, xp: 1200, icon: "fas fa-cookie", name: {ru: "Снек-Император", en: "Snack Emperor"}, desc: {ru: "200 закусок.", en: "200 snacks."} },
    { id: "mh_22", category: "mega_hard", type: "count_cereals", target: 150, xp: 1000, icon: "fas fa-seedling", name: {ru: "Хранитель Зерна", en: "Grain Keeper"}, desc: {ru: "150 круп.", en: "150 cereals."} },
    { id: "mh_23", category: "mega_hard", type: "count_condiments", target: 100, xp: 1000, icon: "fas fa-pepper-hot", name: {ru: "Огненный Лорд", en: "Fire Lord"}, desc: {ru: "100 специй.", en: "100 condiments."} },
    { id: "mh_24", category: "mega_hard", type: "count", target: 700, xp: 1400, icon: "fas fa-warehouse", name: {ru: "Логистический Центр", en: "Logistics Hub"}, desc: {ru: "700 продуктов.", en: "700 items."} },
    { id: "mh_25", category: "mega_hard", type: "any_cook", target: 1500, xp: 3000, icon: "fas fa-meteor", name: {ru: "Кулинарный Бог", en: "Culinary God"}, desc: {ru: "1500 блюд.", en: "1500 dishes."} },
    { id: "mh_26", category: "mega_hard", type: "count_meat", target: 500, xp: 2000, icon: "fas fa-skull-crossbones", name: {ru: "Мясная Вселенная", en: "Meat Universe"}, desc: {ru: "500 мяса.", en: "500 meat."} },
    { id: "mh_27", category: "mega_hard", type: "count_vegetables", target: 600, xp: 2000, icon: "fab fa-envira", name: {ru: "Планета Веганов", en: "Vegan Planet"}, desc: {ru: "600 овощей.", en: "600 veggies."} },
    { id: "mh_28", category: "mega_hard", type: "soup_cook", target: 500, xp: 2000, icon: "fas fa-burn", name: {ru: "Океан Супа", en: "Soup Ocean"}, desc: {ru: "500 супов.", en: "500 soups."} },
    { id: "mh_29", category: "mega_hard", type: "pasta_cook", target: 500, xp: 2000, icon: "fas fa-pizza-slice", name: {ru: "Пастафарианец", en: "Pastafarian"}, desc: {ru: "500 паст.", en: "500 pastas."} },
    { id: "mh_30", category: "mega_hard", type: "dessert_cook", target: 500, xp: 2000, icon: "fas fa-candy-cane", name: {ru: "Сладкая Смерть", en: "Sweet Death"}, desc: {ru: "500 десертов.", en: "500 desserts."} },
    { id: "mh_31", category: "mega_hard", type: "breakfast_cook", target: 500, xp: 2000, icon: "fas fa-sun", name: {ru: "Бесконечное Утро", en: "Infinite Morning"}, desc: {ru: "500 завтраков.", en: "500 breakfasts."} },
    { id: "mh_32", category: "mega_hard", type: "count_seafood", target: 400, xp: 1500, icon: "fas fa-anchor", name: {ru: "Аквамарин", en: "Aquamarine"}, desc: {ru: "400 морепродуктов.", en: "400 seafood."} },
    { id: "mh_33", category: "mega_hard", type: "count_bakery", target: 400, xp: 1500, icon: "fas fa-industry", name: {ru: "Хлебная Галактика", en: "Bread Galaxy"}, desc: {ru: "400 выпечки.", en: "400 bakery."} },
    { id: "mh_34", category: "mega_hard", type: "meat_cook", target: 600, xp: 2000, icon: "fas fa-drumstick-bite", name: {ru: "Мясной Титан", en: "Meat Titan"}, desc: {ru: "600 мясных блюд.", en: "600 meat dishes."} },
    { id: "mh_35", category: "mega_hard", type: "vegetable_cook", target: 600, xp: 2000, icon: "fas fa-leaf", name: {ru: "Дух Природы", en: "Nature Spirit"}, desc: {ru: "600 овощных блюд.", en: "600 veggie dishes."} },
    { id: "mh_36", category: "mega_hard", type: "main_cook", target: 600, xp: 2000, icon: "fas fa-concierge-bell", name: {ru: "Бесконечный Пир", en: "Endless Feast"}, desc: {ru: "600 основных блюд.", en: "600 main courses."} },
    { id: "mh_37", category: "mega_hard", type: "count_dairy", target: 300, xp: 1200, icon: "fas fa-blender", name: {ru: "Молочный Океан", en: "Milk Ocean"}, desc: {ru: "300 молочных.", en: "300 dairy."} },
    { id: "mh_38", category: "mega_hard", type: "count_fruits", target: 300, xp: 1200, icon: "fas fa-lemon", name: {ru: "Фруктовый Рай", en: "Fruit Paradise"}, desc: {ru: "300 фруктов.", en: "300 fruits."} },
    { id: "mh_39", category: "mega_hard", type: "count_cereals", target: 200, xp: 1200, icon: "fas fa-seedling", name: {ru: "Властелин Полей", en: "Lord of Fields"}, desc: {ru: "200 круп.", en: "200 cereals."} },
    { id: "mh_40", category: "mega_hard", type: "count_condiments", target: 150, xp: 1200, icon: "fas fa-pepper-hot", name: {ru: "Властелин Огня", en: "Lord of Fire"}, desc: {ru: "150 специй.", en: "150 condiments."} },
    { id: "mh_41", category: "mega_hard", type: "salad_cook", target: 500, xp: 2000, icon: "fas fa-carrot", name: {ru: "Бог Салатов", en: "Salad God"}, desc: {ru: "500 салатов.", en: "500 salads."} },
    { id: "mh_42", category: "mega_hard", type: "drinks_cook", target: 400, xp: 1800, icon: "fas fa-glass-martini", name: {ru: "Бог Вина", en: "Wine God"}, desc: {ru: "400 напитков.", en: "400 drinks."} },
    { id: "mh_43", category: "mega_hard", type: "snacks_cook", target: 400, xp: 1800, icon: "fas fa-cookie", name: {ru: "Снек-Бог", en: "Snack God"}, desc: {ru: "400 закусок.", en: "400 snacks."} },
    { id: "mh_44", category: "mega_hard", type: "baking_cook", target: 300, xp: 1800, icon: "fas fa-bread-slice", name: {ru: "Бог Выпечки", en: "Baking God"}, desc: {ru: "300 выпечек.", en: "300 bakings."} },
    { id: "mh_45", category: "mega_hard", type: "count", target: 800, xp: 1800, icon: "fas fa-city", name: {ru: "Город Еды", en: "Food City"}, desc: {ru: "800 продуктов.", en: "800 items."} },
    { id: "mh_46", category: "mega_hard", type: "any_cook", target: 2000, xp: 5000, icon: "fas fa-sun", name: {ru: "Создатель", en: "Creator"}, desc: {ru: "2000 блюд.", en: "2000 dishes."} },
    { id: "mh_47", category: "mega_hard", type: "count_meat", target: 800, xp: 3000, icon: "fas fa-dragon", name: {ru: "Мясной Космос", en: "Meat Cosmos"}, desc: {ru: "800 мяса.", en: "800 meat."} },
    { id: "mh_48", category: "mega_hard", type: "count_vegetables", target: 800, xp: 3000, icon: "fab fa-envira", name: {ru: "Зеленая Галактика", en: "Green Galaxy"}, desc: {ru: "800 овощей.", en: "800 veggies."} },
    { id: "mh_49", category: "mega_hard", type: "count_seafood", target: 500, xp: 2000, icon: "fas fa-water", name: {ru: "Владыка Морей", en: "Sea Lord"}, desc: {ru: "500 морепродуктов.", en: "500 seafood."} },
    { id: "mh_50", category: "mega_hard", type: "count_bakery", target: 500, xp: 2000, icon: "fas fa-store", name: {ru: "Вселенская Пекарня", en: "Universal Bakery"}, desc: {ru: "500 выпечки.", en: "500 bakery."} },

    // --- 🕵️ HIDDEN (251-300) ---
    { id: "h_gen_01", category: "hidden", type: "count", target: 0, xp: 500, icon: "fas fa-wind", secret: true, name: {ru: "Пустота", en: "The Void"}, desc: {ru: "0 продуктов (Дзен).", en: "0 items (Zen)."} },
    { id: "h_gen_02", category: "hidden", type: "count", target: 1, xp: 500, icon: "fas fa-user", secret: true, name: {ru: "Одиночка", en: "The Loner"}, desc: {ru: "Всего 1 продукт.", en: "Only 1 item."} },
    { id: "h_gen_03", category: "hidden", type: "count", target: 7, xp: 777, icon: "fas fa-user-secret", secret: true, name: {ru: "Агент 007", en: "Agent 007"}, desc: {ru: "7 продуктов.", en: "7 items."} },
    { id: "h_gen_04", category: "hidden", type: "count", target: 13, xp: 666, icon: "fas fa-ghost", secret: true, name: {ru: "Чертова дюжина", en: "Baker's Dozen"}, desc: {ru: "13 продуктов.", en: "13 items."} },
    { id: "h_gen_05", category: "hidden", type: "count", target: 42, xp: 1000, icon: "fas fa-book", secret: true, name: {ru: "Смысл жизни", en: "The Meaning"}, desc: {ru: "42 продукта.", en: "42 items."} },
    { id: "h_gen_06", category: "hidden", type: "count", target: 69, xp: 690, icon: "fas fa-smile-wink", secret: true, name: {ru: "Найс", en: "Nice"}, desc: {ru: "69 продуктов.", en: "69 items."} },
    { id: "h_gen_07", category: "hidden", type: "count", target: 100, xp: 1000, icon: "fas fa-check-double", secret: true, name: {ru: "Сотник", en: "Centurion"}, desc: {ru: "Ровно 100 продуктов.", en: "Exactly 100 items."} },
    { id: "h_gen_08", category: "hidden", type: "count", target: 365, xp: 1000, icon: "fas fa-calendar", secret: true, name: {ru: "Календарь", en: "Calendar"}, desc: {ru: "365 продуктов.", en: "365 items."} },
    { id: "h_gen_09", category: "hidden", type: "count", target: 404, xp: 404, icon: "fas fa-exclamation-triangle", secret: true, name: {ru: "Не найдено", en: "Not Found"}, desc: {ru: "404 продукта.", en: "404 items."} },
    { id: "h_gen_10", category: "hidden", type: "count", target: 666, xp: 666, icon: "fas fa-fire", secret: true, name: {ru: "Зверь", en: "The Beast"}, desc: {ru: "666 продуктов.", en: "666 items."} },
    { id: "h_gen_11", category: "hidden", type: "count", target: 777, xp: 7777, icon: "fas fa-gem", secret: true, name: {ru: "Джекпот", en: "Jackpot"}, desc: {ru: "777 продуктов.", en: "777 items."} },
    { id: "h_gen_12", category: "hidden", type: "count", target: 911, xp: 911, icon: "fas fa-phone", secret: true, name: {ru: "Полиция", en: "Police"}, desc: {ru: "911 продуктов.", en: "911 items."} },
    { id: "h_gen_13", category: "hidden", type: "count", target: 1337, xp: 1337, icon: "fas fa-laptop-code", secret: true, name: {ru: "Хакер", en: "Leet"}, desc: {ru: "1337 продуктов.", en: "1337 items."} },
    { id: "h_gen_14", category: "hidden", type: "count", target: 1984, xp: 1984, icon: "fas fa-eye", secret: true, name: {ru: "Большой Брат", en: "Big Brother"}, desc: {ru: "1984 продукта.", en: "1984 items."} },
    { id: "h_gen_15", category: "hidden", type: "count", target: 2024, xp: 2024, icon: "fas fa-calendar-alt", secret: true, name: {ru: "Наше время", en: "Our Time"}, desc: {ru: "2024 продукта.", en: "2024 items."} },
    { id: "h_gen_16", category: "hidden", type: "count", target: 3000, xp: 3000, icon: "fas fa-robot", secret: true, name: {ru: "Я люблю тебя 3000", en: "Love u 3000"}, desc: {ru: "3000 продуктов.", en: "3000 items."} },
    { id: "h_gen_17", category: "hidden", type: "count", target: 5000, xp: 5000, icon: "fas fa-mountain", secret: true, name: {ru: "5 Тысяч", en: "5 Grand"}, desc: {ru: "5000 продуктов.", en: "5000 items."} },
    { id: "h_gen_18", category: "hidden", type: "count", target: 8000, xp: 8000, icon: "fas fa-infinity", secret: true, name: {ru: "Бесконечность", en: "Infinity"}, desc: {ru: "8000 продуктов.", en: "8000 items."} },
    { id: "h_gen_19", category: "hidden", type: "count", target: 9000, xp: 9000, icon: "fas fa-bolt", secret: true, name: {ru: "Больше 9000!", en: "Over 9000!"}, desc: {ru: "9000 продуктов.", en: "9000 items."} },
    { id: "h_gen_20", category: "hidden", type: "count", target: 10000, xp: 10000, icon: "fas fa-crown", secret: true, name: {ru: "Десятка", en: "Ten K"}, desc: {ru: "10000 продуктов.", en: "10000 items."} },
    { id: "h_gen_21", category: "hidden", type: "count_meat", target: 666, xp: 1000, icon: "fas fa-drumstick-bite", secret: true, name: {ru: "Адская Кухня", en: "Hell's Kitchen"}, desc: {ru: "666 мяса.", en: "666 meat."} },
    { id: "h_gen_22", category: "hidden", type: "count_vegetables", target: 420, xp: 1000, icon: "fas fa-leaf", secret: true, name: {ru: "Травовед", en: "Herbalist"}, desc: {ru: "420 овощей.", en: "420 veggies."} },
    { id: "h_gen_23", category: "hidden", type: "count_bakery", target: 13, xp: 500, icon: "fas fa-bread-slice", secret: true, name: {ru: "Пекарь-неудачник", en: "Bad Luck Baker"}, desc: {ru: "13 выпечки.", en: "13 bakery."} },
    { id: "h_gen_24", category: "hidden", type: "count_dairy", target: 1, xp: 500, icon: "fas fa-cheese", secret: true, name: {ru: "Одинокий сыр", en: "Lonely Cheese"}, desc: {ru: "1 молочный продукт.", en: "1 dairy."} },
    { id: "h_gen_25", category: "hidden", type: "count_fruits", target: 33, xp: 500, icon: "fas fa-lemon", secret: true, name: {ru: "33 Коровы", en: "33 Cows"}, desc: {ru: "33 фрукта.", en: "33 fruits."} },
    { id: "h_gen_26", category: "hidden", type: "any_cook", target: 0, xp: 100, icon: "fas fa-bed", secret: true, name: {ru: "Лентяй", en: "Lazy"}, desc: {ru: "0 блюд (Голод).", en: "0 cooked (Starving)."} },
    { id: "h_gen_27", category: "hidden", type: "any_cook", target: 77, xp: 777, icon: "fas fa-star", secret: true, name: {ru: "Семерки", en: "Sevens"}, desc: {ru: "77 блюд.", en: "77 dishes."} },
    { id: "h_gen_28", category: "hidden", type: "any_cook", target: 111, xp: 111, icon: "fas fa-align-justify", secret: true, name: {ru: "Забор", en: "Picket Fence"}, desc: {ru: "111 блюд.", en: "111 dishes."} },
    { id: "h_gen_29", category: "hidden", type: "any_cook", target: 222, xp: 222, icon: "fas fa-align-justify", secret: true, name: {ru: "Утки", en: "Ducks"}, desc: {ru: "222 блюда.", en: "222 dishes."} },
    { id: "h_gen_30", category: "hidden", type: "any_cook", target: 333, xp: 333, icon: "fas fa-align-justify", secret: true, name: {ru: "Тройки", en: "Threes"}, desc: {ru: "333 блюда.", en: "333 dishes."} },
    { id: "h_gen_31", category: "hidden", type: "any_cook", target: 999, xp: 1999, icon: "fas fa-arrow-up", secret: true, name: {ru: "Перевертыш", en: "Upside Down"}, desc: {ru: "999 блюд.", en: "999 dishes."} },
    { id: "h_gen_32", category: "hidden", type: "any_cook", target: 123, xp: 123, icon: "fas fa-sort-numeric-down", secret: true, name: {ru: "Счет", en: "Counting"}, desc: {ru: "123 блюда.", en: "123 dishes."} },
    { id: "h_gen_33", category: "hidden", type: "count_cereals", target: 0, xp: 100, icon: "fas fa-ban", secret: true, name: {ru: "Без глютена", en: "Gluten Free"}, desc: {ru: "0 круп.", en: "0 cereals."} },
    { id: "h_gen_34", category: "hidden", type: "count_meat", target: 0, xp: 100, icon: "fas fa-leaf", secret: true, name: {ru: "Веган", en: "Vegan"}, desc: {ru: "0 мяса.", en: "0 meat."} },
    { id: "h_gen_35", category: "hidden", type: "count_dairy", target: 0, xp: 100, icon: "fas fa-ban", secret: true, name: {ru: "Лактоза-фри", en: "Lactose Free"}, desc: {ru: "0 молочных.", en: "0 dairy."} },
    { id: "h_gen_36", category: "hidden", type: "dessert_cook", target: 0, xp: 100, icon: "fas fa-ban", secret: true, name: {ru: "Диета", en: "Diet"}, desc: {ru: "0 десертов.", en: "0 desserts."} },
    { id: "h_gen_37", category: "hidden", type: "soup_cook", target: 99, xp: 900, icon: "fas fa-mug-hot", secret: true, name: {ru: "Почти Сотня", en: "Almost 100"}, desc: {ru: "99 супов.", en: "99 soups."} },
    { id: "h_gen_38", category: "hidden", type: "pasta_cook", target: 88, xp: 800, icon: "fas fa-infinity", secret: true, name: {ru: "Макаронный Монстр", en: "Spaghetti Monster"}, desc: {ru: "88 паст.", en: "88 pastas."} },
    { id: "h_gen_39", category: "hidden", type: "drinks_cook", target: 50, xp: 500, icon: "fas fa-glass-martini-alt", secret: true, name: {ru: "Полтинник", en: "Fifty"}, desc: {ru: "50 напитков.", en: "50 drinks."} },
    { id: "h_gen_40", category: "hidden", type: "snacks_cook", target: 42, xp: 420, icon: "fas fa-cookie", secret: true, name: {ru: "Закуска жизни", en: "Life Snack"}, desc: {ru: "42 закуски.", en: "42 snacks."} },
    { id: "h_gen_41", category: "hidden", type: "count_condiments", target: 11, xp: 110, icon: "fas fa-pepper-hot", secret: true, name: {ru: "Одиннадцать друзей", en: "Ocean's 11"}, desc: {ru: "11 специй.", en: "11 condiments."} },
    { id: "h_gen_42", category: "hidden", type: "count_seafood", target: 20000, xp: 20000, icon: "fas fa-water", secret: true, name: {ru: "20 тысяч лье", en: "20000 Leagues"}, desc: {ru: "20000 морепродуктов.", en: "20000 seafood."} },
    { id: "h_gen_43", category: "hidden", type: "count", target: 555, xp: 555, icon: "fas fa-phone-alt", secret: true, name: {ru: "Кино", en: "Movie Phone"}, desc: {ru: "555 продуктов.", en: "555 items."} },
    { id: "h_gen_44", category: "hidden", type: "any_cook", target: 366, xp: 366, icon: "fas fa-calendar-check", secret: true, name: {ru: "Високосный год", en: "Leap Year"}, desc: {ru: "366 блюд.", en: "366 dishes."} },
    { id: "h_gen_45", category: "hidden", type: "count", target: 112, xp: 112, icon: "fas fa-ambulance", secret: true, name: {ru: "Спасатель", en: "Rescuer"}, desc: {ru: "112 продуктов.", en: "112 items."} },
    { id: "h_gen_46", category: "hidden", type: "count_bakery", target: 101, xp: 101, icon: "fas fa-dog", secret: true, name: {ru: "Далматинец", en: "Dalmatian"}, desc: {ru: "101 выпечка.", en: "101 bakery."} },
    { id: "h_gen_47", category: "hidden", type: "count_fruits", target: 5, xp: 5, icon: "fas fa-star", secret: true, name: {ru: "Пять Звезд", en: "Five Stars"}, desc: {ru: "5 фруктов (Скрытое).", en: "5 fruits (Hidden)."} },
    { id: "h_gen_48", category: "hidden", type: "count_meat", target: 888, xp: 888, icon: "fas fa-infinity", secret: true, name: {ru: "Бесконечное Мясо", en: "Infinite Meat"}, desc: {ru: "888 мяса.", en: "888 meat."} },
    { id: "h_gen_49", category: "hidden", type: "any_cook", target: 1111, xp: 1111, icon: "fas fa-grip-lines", secret: true, name: {ru: "Штакетник", en: "Pickets"}, desc: {ru: "1111 блюд.", en: "1111 dishes."} },
    { id: "h_gen_50", category: "hidden", type: "count", target: 1, xp: 9999, icon: "fas fa-gem", secret: true, name: {ru: "Избранный", en: "The One"}, desc: {ru: "Всего 1 продукт (Редкость).", en: "Just 1 item (Rare)."} }
];